// flow-typed signature: f54425d963ea2844106052f9978b0dda
// flow-typed version: <<STUB>>/gdax_v^0.4.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gdax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gdax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gdax/lib/clients/authenticated' {
  declare module.exports: any;
}

declare module 'gdax/lib/clients/public' {
  declare module.exports: any;
}

declare module 'gdax/lib/clients/websocket' {
  declare module.exports: any;
}

declare module 'gdax/lib/orderbook_sync' {
  declare module.exports: any;
}

declare module 'gdax/lib/orderbook' {
  declare module.exports: any;
}

declare module 'gdax/lib/request_signer' {
  declare module.exports: any;
}

declare module 'gdax/tests/authenticated' {
  declare module.exports: any;
}

declare module 'gdax/tests/lib/ws_testserver' {
  declare module.exports: any;
}

declare module 'gdax/tests/orderbook_sync_test' {
  declare module.exports: any;
}

declare module 'gdax/tests/orderbook' {
  declare module.exports: any;
}

declare module 'gdax/tests/public_client' {
  declare module.exports: any;
}

declare module 'gdax/tests/websocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gdax/index' {
  declare module.exports: $Exports<'gdax'>;
}
declare module 'gdax/index.js' {
  declare module.exports: $Exports<'gdax'>;
}
declare module 'gdax/lib/clients/authenticated.js' {
  declare module.exports: $Exports<'gdax/lib/clients/authenticated'>;
}
declare module 'gdax/lib/clients/public.js' {
  declare module.exports: $Exports<'gdax/lib/clients/public'>;
}
declare module 'gdax/lib/clients/websocket.js' {
  declare module.exports: $Exports<'gdax/lib/clients/websocket'>;
}
declare module 'gdax/lib/orderbook_sync.js' {
  declare module.exports: $Exports<'gdax/lib/orderbook_sync'>;
}
declare module 'gdax/lib/orderbook.js' {
  declare module.exports: $Exports<'gdax/lib/orderbook'>;
}
declare module 'gdax/lib/request_signer.js' {
  declare module.exports: $Exports<'gdax/lib/request_signer'>;
}
declare module 'gdax/tests/authenticated.js' {
  declare module.exports: $Exports<'gdax/tests/authenticated'>;
}
declare module 'gdax/tests/lib/ws_testserver.js' {
  declare module.exports: $Exports<'gdax/tests/lib/ws_testserver'>;
}
declare module 'gdax/tests/orderbook_sync_test.js' {
  declare module.exports: $Exports<'gdax/tests/orderbook_sync_test'>;
}
declare module 'gdax/tests/orderbook.js' {
  declare module.exports: $Exports<'gdax/tests/orderbook'>;
}
declare module 'gdax/tests/public_client.js' {
  declare module.exports: $Exports<'gdax/tests/public_client'>;
}
declare module 'gdax/tests/websocket.js' {
  declare module.exports: $Exports<'gdax/tests/websocket'>;
}
