// flow-typed signature: 558b6843aef4461749343c2f02127bb1
// flow-typed version: <<STUB>>/react-web3_v^0.3.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-web3/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-web3/dist/index.js' {
  declare module.exports: $Exports<'react-web3/dist/index'>;
}
