// flow-typed signature: 4755679062e05ee9466e7cf7976971ed
// flow-typed version: <<STUB>>/winston-loggly-bulk_v^1.4.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-loggly-bulk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-loggly-bulk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-loggly-bulk/lib/winston-loggly' {
  declare module.exports: any;
}

declare module 'winston-loggly-bulk/test/winston-loggly-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-loggly-bulk/lib/winston-loggly.js' {
  declare module.exports: $Exports<'winston-loggly-bulk/lib/winston-loggly'>;
}
declare module 'winston-loggly-bulk/test/winston-loggly-test.js' {
  declare module.exports: $Exports<'winston-loggly-bulk/test/winston-loggly-test'>;
}
